# Generated by Django 5.2.5 on 2025-08-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
    ]
